receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: Detailed

  otlp:
    endpoint: "oap:11800"  # SkyWalking OAP gRPC
    tls:
      insecure: true        # OAP gRPC is plain text

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
